# Generated by Django 3.2.13 on 2022-05-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_unit', models.CharField(max_length=200, verbose_name='Nama Unit')),
                ('unit', models.CharField(max_length=10, verbose_name='Unit')),
                ('nama_mesin', models.CharField(max_length=200, verbose_name='Nama Mesin')),
                ('daya_mampu', models.IntegerField(verbose_name='Daya Mampu')),
                ('is_sewa', models.BooleanField(verbose_name='Sewa')),
            ],
        ),
    ]
