# Generated by Django 3.2.13 on 2022-05-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesin',
            name='daya_mampu',
            field=models.IntegerField(verbose_name='Daya Mampu (kW)'),
        ),
    ]
