# Generated by Django 3.2.13 on 2022-05-16 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_mesin_daya_mampu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_unit', models.CharField(max_length=200, verbose_name='Nama Unit')),
            ],
        ),
        migrations.RemoveField(
            model_name='mesin',
            name='nama_unit',
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix_cost', models.IntegerField(blank=True, null=True, verbose_name='Total Fix Cost')),
                ('time_base_vcost', models.IntegerField(blank=True, null=True, verbose_name='Total Time Base V-Cost')),
                ('sfc_50', models.IntegerField(blank=True, null=True, verbose_name='SFC 50% DMN')),
                ('sfc_75', models.IntegerField(blank=True, null=True, verbose_name='SFC 75% DMN')),
                ('sfc_100', models.IntegerField(blank=True, null=True, verbose_name='SFC 100% DMN')),
                ('herga_sewa', models.IntegerField(blank=True, null=True, verbose_name='Harga Sewa per kWh')),
                ('pajak_air', models.IntegerField(blank=True, null=True, verbose_name='Pajak Air Permukaan')),
                ('susut_trafo', models.IntegerField(blank=True, null=True, verbose_name='Susut Trafo')),
                ('susut_jaringan', models.IntegerField(blank=True, null=True, verbose_name='Susut Jaringan (%)')),
                ('mesin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mesin', verbose_name='Nama Mesin')),
            ],
        ),
        migrations.AddField(
            model_name='mesin',
            name='nama_unit_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.unit', verbose_name='Nama Unit'),
            preserve_default=False,
        ),
    ]
