# Generated by Django 3.2.13 on 2022-05-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220516_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='herga_sewa',
        ),
        migrations.AddField(
            model_name='cost',
            name='harga_sewa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Harga Sewa per kWh (Khusus Sewa)'),
        ),
    ]
