# Generated by Django 3.2.13 on 2022-05-19 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_feeder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Har',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumat', models.CharField(max_length=20, verbose_name='Jumat')),
                ('sabtu', models.CharField(max_length=20, verbose_name='Sabtu')),
                ('minggu', models.CharField(max_length=20, verbose_name='Minggu')),
                ('senin', models.CharField(max_length=20, verbose_name='Senin')),
                ('selasa', models.CharField(max_length=20, verbose_name='Selasa')),
                ('rabu', models.CharField(max_length=20, verbose_name='Rabu')),
                ('kamis', models.CharField(max_length=20, verbose_name='Kamis')),
                ('tanggal_jumat', models.DateField(verbose_name='Tanggal')),
                ('mesin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mesin', verbose_name='Nama Mesin')),
            ],
        ),
    ]
