# Generated by Django 3.2.13 on 2022-05-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_har'),
    ]

    operations = [
        migrations.AlterField(
            model_name='har',
            name='tanggal_jumat',
            field=models.DateField(verbose_name='Tanggal Mulai'),
        ),
    ]
