# Generated by Django 3.2.13 on 2022-05-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_har_tanggal_jumat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='har',
            name='jumat',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('TO', 'TO'), ('SO', 'SO'), ('MO', 'MO'), ('PdM', 'PdM'), ('CM', 'CM'), ('Standby', 'Standby')], default='Standby', max_length=20, verbose_name='Jumat'),
        ),
        migrations.AlterField(
            model_name='har',
            name='kamis',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('TO', 'TO'), ('SO', 'SO'), ('MO', 'MO'), ('PdM', 'PdM'), ('CM', 'CM'), ('Standby', 'Standby')], default='Standby', max_length=20, verbose_name='Kamis'),
        ),
        migrations.AlterField(
            model_name='har',
            name='minggu',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('TO', 'TO'), ('SO', 'SO'), ('MO', 'MO'), ('PdM', 'PdM'), ('CM', 'CM'), ('Standby', 'Standby')], default='Standby', max_length=20, verbose_name='Minggu'),
        ),
        migrations.AlterField(
            model_name='har',
            name='rabu',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('TO', 'TO'), ('SO', 'SO'), ('MO', 'MO'), ('PdM', 'PdM'), ('CM', 'CM'), ('Standby', 'Standby')], default='Standby', max_length=20, verbose_name='Rabu'),
        ),
        migrations.AlterField(
            model_name='har',
            name='sabtu',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('TO', 'TO'), ('SO', 'SO'), ('MO', 'MO'), ('PdM', 'PdM'), ('CM', 'CM'), ('Standby', 'Standby')], default='Standby', max_length=20, verbose_name='Sabtu'),
        ),
        migrations.AlterField(
            model_name='har',
            name='selasa',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('TO', 'TO'), ('SO', 'SO'), ('MO', 'MO'), ('PdM', 'PdM'), ('CM', 'CM'), ('Standby', 'Standby')], default='Standby', max_length=20, verbose_name='Selasa'),
        ),
        migrations.AlterField(
            model_name='har',
            name='senin',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('TO', 'TO'), ('SO', 'SO'), ('MO', 'MO'), ('PdM', 'PdM'), ('CM', 'CM'), ('Standby', 'Standby')], default='Standby', max_length=20, verbose_name='Senin'),
        ),
    ]
